plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

permalink: /:path/:basename:output_ext

baseurl: ""
url: "https://algotradinglib.com"

safe: false

liquid:
  error_mode: strict
  strict_filters: true

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

include:
  - "*/locales.yml"
  - "robots.txt"

generators:
  - AlgoTradingPageGenerator